name: Auto Build Image

env:
  ONLINE_REGISTER: ghcr.io
  BUILD_PLATFORM: linux/amd64,linux/arm64
  ONLINE_REGISTER_USER: ${{ github.actor }}
  ONLINE_REGISTER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
      tag:
        required: true
        type: string
      push:
        required: false
        type: boolean

permissions: write-all

jobs:
  build_and_push_prs:
    runs-on: ubuntu-latest
    # run if filters.src was changed
    outputs:
      imageTag: ${{ steps.tag.outputs.tag }}

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: Login to online register
        uses: docker/login-action@v3.0.0
        if: ${{ steps.tag.outputs.push == 'true' }}
        with:
          username: ${{ env.ONLINE_REGISTER_USER }}
          password: ${{ env.ONLINE_REGISTER_PASSWORD }}
          registry: ${{ env.ONLINE_REGISTER }}

      # checkout the changed code
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          ref: ${{ inputs.tag }}

      - name: Getting Build Arg
        id: arg
        continue-on-error: false
        run: |
          GIT_COMMIT_VERSION=$( git show -s --format='format:%H')
          GIT_COMMIT_TIME=$( git show -s --format='format:%aI')
          echo ::set-output name=commit_version::${GIT_COMMIT_VERSION}
          echo ::set-output name=commit_time::${GIT_COMMIT_TIME}

      # =============  get cache ===========
      # Load Golang cache build from GitHub
      # Cache dependencies and build outputs in GitHub Actions
      # the github will keep the cache for 7 days at most
      # we could see cache-hit result for this step
      - name: Load Golang cache build from GitHub
        uses: actions/cache@v3
        id: cache
        with:
          # if find the cache mapping to "key" , will restore to "path"
          # when the key doesn't match an existing cache. A list of restore-keys is useful when you are restoring a cache from another branch
          path: /tmp/.cache/${{ matrix.name }}
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}-${{ matrix.name }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}-${{ matrix.name }}-
            ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}-
            ${{ runner.os }}-go-

      - name: Create cache directory
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        shell: bash
        run: |
          mkdir -p /tmp/.cache

      # Import GitHub's cache build to docker cache
      - name: Copy Golang cache to docker cache
        uses: docker/build-push-action@v5.0.0
        with:
          context: /tmp/.cache/
          file: ./images/cache/Dockerfile
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push: false
          platforms: linux/amd64
          target: import-cache

      # ========== image build
      # build normal image
      - name: Image Build
        uses: docker/build-push-action@v5.0.0
        continue-on-error: false
        id: docker_build_master
        with:
          context: .
          file: ./Dockerfile
          # Only push when the event name was a GitHub push, this is to avoid
          # re-pushing the image tags when we only want to re-create the Golang
          # docker cache after the workflow "Image CI Cache Cleaner" was terminated.
          push: ${{ inputs.push }}
          provenance: false
          platforms: linux/amd64,linux/arm64
          github-token: ${{ secrets.GITHUB_TOKEN }}
          tags: |
            ${{ env.ONLINE_REGISTER }}/${{ github.repository }}/cilium-chaining:${{ inputs.tag }}
          build-args: |
            GIT_COMMIT_VERSION=${{ steps.arg.outputs.commit_version }}
            GIT_COMMIT_TIME=${{ steps.arg.outputs.commit_time }}
            VERSION=${{ steps.tag.outputs.tag }}

      - name: Image Releases digests
        if: ${{ github.event_name != 'pull_request_target' }}
        shell: bash
        run: |
          mkdir -p image-digest/
          echo "${{ env.ONLINE_REGISTER }}/${{ github.repository }}/${{ matrix.name }}-ci:${{ steps.tag.outputs.tag }}@${{ steps.docker_build_ci_master.outputs.digest }}" > image-digest/${{ matrix.name }}.txt
          echo "${{ env.ONLINE_REGISTER }}/${{ github.repository }}/${{ matrix.name }}-ci:${{ steps.tag.outputs.tag }}-race@${{ steps.docker_build_ci_master_detect_race_condition.outputs.digest }}" >> image-digest/${{ matrix.name }}.txt

      # Upload artifact digests
      - name: Upload artifact digests
        uses: actions/upload-artifact@v3.1.3
        with:
          name: image-digest-${{ matrix.name }}
          path: image-digest
          retention-days: 1

      # Upload artifact race images tar
      - name: Upload artifact race image tar
        uses: actions/upload-artifact@v3.1.3
        with:
          name: image-tar-${{ matrix.name }}
          path: /tmp/${{ matrix.name }}-race.tar
          retention-days: 1

      # =============  restore cache ===========
      # Store docker's golang's cache build locally only on the main branch
      - name: Store ${{ matrix.name }} Golang cache build locally
        if: ${{ github.event_name != 'pull_request_target' && steps.cache.outputs.cache-hit != 'true' }}
        uses: docker/build-push-action@v5.0.0
        with:
          context: .
          file: ./images/cache/Dockerfile
          push: false
          outputs: type=local,dest=/tmp/docker-cache
          platforms: linux/amd64
          target: export-cache

      # Store docker's golang's cache build locally only on the main branch
      - name: Store  Golang cache in GitHub cache path
        if: ${{ github.event_name != 'pull_request_target' && steps.cache.outputs.cache-hit != 'true' }}
        shell: bash
        run: |
          mkdir -p /tmp/.cache/
          if [ -f /tmp/docker-cache/tmp/go-build-cache.tar.gz ]; then
            cp /tmp/docker-cache/tmp/go-build-cache.tar.gz /tmp/.cache/
          fi
          if [ -f /tmp/docker-cache/tmp/go-pkg-cache.tar.gz ]; then
            cp /tmp/docker-cache/tmp/go-pkg-cache.tar.gz /tmp/.cache/
          fi

  image-digests:
    name: Display Digests
    runs-on: ubuntu-latest
    needs: build_and_push_prs
    steps:
      - name: Downloading Image Digests
        shell: bash
        run: |
          mkdir -p image-digest/

      - name: Download digests of all images built
        uses: actions/download-artifact@v3
        with:
          path: image-digest/
          name: image-digest-spiderpool-agent

      - name: Download digests of all images built
        uses: actions/download-artifact@v3
        with:
          path: image-digest/
          name: image-digest-spiderpool-controller

      - name: Image Digests Output
        shell: bash
        run: |
          cd image-digest/
          find -type f | sort | xargs -d '\n' cat
