{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cilium-chaining.serviceAccountName" . }}
  namespace:  {{ .Release.Namespace }}
  labels:
    {{- include "cilium-chaining.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
