name: Auto Build Latest Image

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - main

permissions: write-all

jobs:
  call-workflow:
    uses: ./.github/workflows/call-image-build.yaml
    if: ${{ github.event_name = 'push' }}
    with:
      ref: ${{ github.ref }}
      tag: latest
      push: true
    secrets: inherit

  call-workflow:
    uses: ./.github/workflows/call-image-build.yaml
    if: ${{ github.event_name == 'pull_request' }}
    with:
      ref: ${{ github.ref }}
      tag: ${{ github.event.pull_request.head.sha }}
      push: false
    secrets: inherit
