name: e2e

env:
  ONLINE_REGISTER: ghcr.io
  HELM_VERSION: v3.13.0

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - main

jobs:
  call-build-pr:
    uses:  ./.github/workflows/call-image-build.yaml
    if: ${{ github.event_name == 'pull_request_target' }}
    with:
      ref: ${{ github.ref }}
      tag: ${{ github.event.pull_request.head.sha }}
      push: false
      ci: true
    secrets: inherit

  call-build-main:
    uses:  ./.github/workflows/call-image-build.yaml
    if: ${{ github.event_name == 'push' }}
    with:
     ref: ${{ github.ref }}
     tag: ${{ github.sha }}
     push: false
     ci: true
    secrets: inherit

  call_e2e:
    runs-on: ubuntu-latest
    needs: [call-build-pr,call-build-main]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          ref: ${{ github.ref }}

      - name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version: 1.21.2
          id: go

      # The cached helm binary path is prepended to the PATH environment variable as well as stored in the helm-path output variable
      # https://github.com/Azure/setup-helm
      - name: Set up Helm
        uses: azure/setup-helm@v3.5
        with:
          version: ${{ env.HELM_VERSION }}

      - name: Download ci image
        uses: actions/download-artifact@v3
        with:
          name: image-e2e-tar
          path: .tmp

      - name: Load Image to docker
        run: |
          docker load -i .tmp/images.tar
          docker images

      # https://github.com/actions/setup-python
      - name: Set up Python
        uses: actions/setup-python@v4.7.0
        with:
          python-version: 3.8
          architecture: x64

      # https://github.com/helm/chart-testing-action
      # Pre-requisites: A GitHub repo containing a directory with your Helm charts (e.g: charts)
      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.4.0
        with:
          # CT version
          version: v3.9.0

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          # https://github.com/helm/chart-testing-action/issues/25
          # if the default branch is not master , the CLI exits with error
          changed=$( ct list-changed --target-branch ${{ github.ref }}  )
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi

      # version checking, YAML schema validation on 'Chart.yaml', YAML linting on 'Chart.yaml'
      # and 'values.yaml', and maintainer validation
      - name: Run chart-testing (lint)
        run: ct lint --debug --target-branch=${{ github.ref }} --check-version-increment=false

      # https://github.com/helm/kind-action
      - name: Create Kind cluster
        if: steps.list-changed.outputs.changed == 'true'
        uses: helm/kind-action@v1.8.0
        with:
          wait: 120s

      #  It automatically detects charts changed
      - name: Run chart-testing (install)
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          kind load docker-image ${{ env.ONLINE_REGISTER }}/${{ github.repository }}:${{ github.event.pull_request.head.sha }}
          ct install --debug --target-branch ${{ github.ref }} --namespace kube-system \
              --helm-extra-args "--timeout 400s --cilium.image.tag=${{ github.event.pull_request.head.sha }}"
